baseURL = "https://www.bitzot.com"
defaultContentLanguage = "en"
title = "bitzot"
style = "default"
theme = "hugo-universal-theme"
languageCode = "en-us"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="blog"
    name = "Blog"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url  = "/faq/"
    weight = 3

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 4

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"